base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

news_list/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'item/(\d+)/$', views.item, name = 'item'),
]

student_union/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('event-list/', include('event_list.urls')),
    path('event-register/', include('event_register.urls')),
    path('daftar/', include('member_register.urls')),
    path('news/', include('news_list.urls')),
    path('about/', include(('testimoni.urls', 'about'), namespace='about')),
    path('login/', include('login_system.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

news_list/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=200)
    pic = models.TextField(max_length=900, default='')
    url = models.TextField()

news_list/views.py
from django.shortcuts import render, HttpResponse
from django.http import Http404, HttpResponseRedirect
from .models import News

# Create your views here.
def index(request):
    news = News.objects.all()
    return render(request, 'news_list/news.html', {"news" : news})

def item(request, offset):
    try:
        news_select = News.objects.get(pk=offset)
        response = {}
        response['title'] = news_select.title
        response['details'] = news_select.url
        response['photo'] = news_select.pic
        html = 'news_list/news_item.html'
        return render(request, html, response)
    except:
        return HttpResponseRedirect('/news')
    

templates/news_list/news.html
{% extends "base/base.html" %}
{%load staticfiles%}

{% block content %}

<div class = "container-fluid">

    <div class ="row justify-content-center">
        <div class = "col-sm-12 col-md-6 col-lg-4">
            <br>
            <div class="embed-responsive embed-responsive-4by3">
                <iframe class="embed-responsive-item" src="https://youtube.com/embed/h3G7buCae8c?rel=0&autoplay=1" allow="autoplay; encrypted-media"></iframe>
            </div>
        </div>
        
        <div class = "col-sm-12 col-md-6 col-lg-4">
            <h1 style="padding-top: 50px; color: white;" >VIVA - Djakarta Warehouse Project X (DWPX) 2018 </h1><p> akhirnya resmi digelar di Garuda Wisnu Kencana (GWK) Bali hari ini, Jumat, 7 Desember 2018. Acara akan dihelat hingga Minggu, 9 Desember 2018. Meski pertama kali diadakan di Bali, antusiasme penonton pada hari pertama begitu besar. Antrean kendaraan mengular di sepanjang jalan menuju venue acara. Muda-mudi berdesakan di setiap area panggung, menari dan menikmati musik yang berdentum kencang. (Courtesy of VIVA.CO.ID, Youtube)
            <br><br> <a href="https://www.youtube.com/watch?v=h3G7buCae8c" class="btn text-light" style = "background-color: #FF4757;">Watch More</a>
        </div> 

    </div>
    <hr>
    <br>
    <div class ="row justify-content-center">
        {% for items in news %}

        <div class = "col-sm-12 col-md-4 col-lg-4" style="width: 7rem " >
                <img class="card-img-top" src={{ items.pic }} alt="Card image cap">
                <p class="h1"> <a href="{% url 'news:item' items.pk %}" style="color:white; text-align: center;"> {{ items.title }} </a></p>
                <p>{{ items.url|truncatechars_html:100}}<br>

        </div>
        
        {% endfor %}

    </div>
    <br><br><br>

</div>

{% endblock %}

templates/news_list/news_item.html
{% extends "base/base.html" %}
{%load staticfiles%}

{% block content %}
<div class = "container-fluid">
	<div class = "row justify-content-center">
		<div class = "col-sm-12 col-md-12 col-lg-12" >
			<br><br><br><br>
			<p class="h1"> {{ title }}</p>
			<hr style = "background-color: #ffffff"><br>
			<img src= {{ photo }} class="img-fluid rounded mx-auto d-block"><br>
			<p> {{ details }}  </p><br>
			<br>
		</div>
	</div>
</div>

<div class="w-100"></div>


{% endblock %}